# Generated by Django 5.2.7 on 2025-10-19 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField()),
                ('dialogue', models.JSONField()),
                ('target_line', models.CharField(max_length=500)),
                ('speaker', models.CharField(max_length=100)),
                ('image_url', models.URLField(max_length=1000)),
                ('tokens_used', models.IntegerField(default=1)),
                ('subject_description', models.TextField(blank=True)),
                ('setting_and_scene', models.TextField(blank=True)),
                ('action_or_expression', models.TextField(blank=True)),
                ('camera_and_style', models.TextField(blank=True)),
                ('full_image_prompt', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
